# Use wildcard "*" to expose all endpoints
# Can also expose individual end points with a comma-delimited list

# management.endpoints.web.exposure.include=health,info
management.endpoints.web.exposure.include=*
management.info.env.enabled = true

info.app.name = Kien's app
info.app.description = This is a test app
info.app.version = 1.0.0